export { default as babel }      from './wp-rules/babel';
export { default as javascript } from './wp-rules/javascript';
export { default as scss }       from './wp-rules/scss';
export { default as less }       from './wp-rules/less';
export { default as images }     from './wp-rules/images';
export { default as videos }     from './wp-rules/videos';
export { default as docs }       from './wp-rules/docs';
export { default as fonts }      from './wp-rules/fonts';
export { default as twig }       from './wp-rules/twig';
